server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki.my:3100/loki/api/v1/push

#local GitLab shell logs
scrape_configs:
- job_name: gitlab-shell
  static_configs:
  - targets:
    - localhost
    labels:
      job: gitlab-shell
      __path__: /var/log/gitlab/gitlab-shell/gitlab-shell.log
