stages:
    - build
    - deploy-stage

build:
  stage: build
  script:
    - mvn clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - "target/*.jar"
    untracked: true
    when: on_success
    access: all
    expire_in: "3 days"
  tags:
    - docker-runner

deploy_stage:
  stage: deploy-stage
  script:
    - sudo docker compose up --force-recreate --build -d
    - sudo docker image prune -f
  tags:
    - prod-runner
  dependencies:
    - "build"
