#version: "3"

services:
  nginx-proxy:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:ready
    container_name: app
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/TTGAdmin
      POSTGRE_PASSWORD: postgres
    expose:
      - 8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: TTGAdmin
#    ports:
#      - 5432:5432
    expose:
      - 5432
    volumes:
      - /pgdata:/var/lib/postgresql/data