#version: "3"

services:
  nginx-proxy:
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:ready
    container_name: app
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/TTGAdmin
      POSTGRE_PASSWORD: postgres
    expose:
      - 8080
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: TTGAdmin
#    ports:
#      - 5432:5432
    expose:
      - 5432
    volumes:
      - /pgdata:/var/lib/postgresql/data
    restart: always

  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4:7
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - /pgadmin-data:/var/lib/pgadmin
  #   restart: always
