global:
  scrape_interval: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "prometheus host"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "production server"
    static_configs:
      - targets: ["prod.docker:8080"]
