global:
  scrape_interval: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: "prometheus host"
    static_configs:
      - targets:
          - "localhost:9090"
  
  - job_name: "coders docker"
    static_configs:
      - targets: ["coders.docker:8080"]

  - job_name: gitlab_metrics
    metrics_path: "/-/metrics"
    scheme: http
    static_configs:
      - targets:
        - gitlab.my
  - job_name: gitlab_services
    static_configs:
      - targets: ["gitlab.my:8060"]
        labels:
          name: "nginx"
      - targets: ["gitlab.my:9121"]
        labels:
          name: "redis"
      - targets: ["gitlab.my:9187"]
        labels:
          name: "postgres"
      - targets: ["gitlab.my:9100"]
        labels:
          name: "node"
      - targets: ["gitlab.my:9229"]
        labels:
          name: "gitlab-workhorse"
      - targets: ["gitlab.my:8082"]
        labels:
          name: "gitlab-sidekiq"
      - targets: ["gitlab.my:9236"]
        labels:
          name: "gitaly"

  - job_name: gitlab_exporter_database
    metrics_path: "/database"
    static_configs:
      - targets:
        - gitlab.my:9168
  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
      - targets:
        - gitlab.my:9168
