- name: Developers server configuration
  hosts: coders

  vars_files:
    - vars.yml
  
  tasks:

    - name: Create ssh key pair for using git
      community.crypto.openssh_keypair:
        path: "{{ path_to_store_git_ssh_keys }}"
        type: ed25519
        state: present
      register: ssh_key_pair

    - name: Install python3-pip
      apt:
        pkg:
          - python3-pip
        update_cache: yes
      become: yes
    
    - name: Install python-gitlab
      pip:
        name:
          - python-gitlab

    - name: Deploy an ssh key for project
      community.general.gitlab_deploy_key:
        api_url: "http://{{ hostvars['gitlab']['ansible_host'] }}"
        api_username: root
        api_password: "{{ gitlab_root_pass }}"
        project: "{{ group_name }}/{{ proj_name }}"
        title: "{{ ssh_key_title }}"
        state: present
        can_push: true
        key: "{{ ssh_key_pair.public_key | string }}"

    - ansible.builtin.import_tasks:
        file: docker-install.yml
      become: yes

    - name: Create folder /coders if not exist
      file:
        path: /coders
        mode: 0766
        state: directory
      become: yes

    - name: Copy source files to server
      copy:
        src: coders/
        dest: /coders
        remote_src: false
      become: yes
    
##### конфигурируем докер для мониторинга из Прометеуса ( начало )
    - name: Pull cAdvisor image
      community.docker.docker_image:
        name: gcr.io/cadvisor/cadvisor:v0.49.1
        source: pull

    - name: Running cAdvisor container to export docker metrics to Prometheus
      community.docker.docker_container:
        name: cadvisor
        restart_policy: always
        image: gcr.io/cadvisor/cadvisor:v0.49.1
        detach: true
        published_ports:
          - 8080:8080
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/disk/:/dev/disk:ro
        state: started
      become: yes
##### конфигурируем докер для мониторинга из Прометеуса ( конец )

    - name: Build Coders image
      shell: "docker build --build-arg user={{ ansible_user_id }} --build-arg ip={{ hostvars['gitlab']['ansible_host'] }} -t coders-image:latest /coders -f /coders/Dockerfile.coders"
      become: yes
    # - name: Build Coders image
    #   community.docker.docker_image:
    #     build:
    #       dockerfile: /coders/Dockerfile.coders
    #       path: /
    #       args:
    #         user: "{{ ansible_user_id }}"
    #     source: build
    #     name: coders-image
    #     tag: latest
    #     state: present
    #   become: yes

    - name: "Create Coders container #1"
      community.docker.docker_container:
        name: coders_1
        restart_policy: always
        image: coders-image:latest
        network_mode: host
        env:
          GITLAB_IP: "{{ hostvars['gitlab']['ansible_host'] }}"
          # GITLAB_TOKEN: "{{ gitlab_root_token }}"
          GITLAB_GROUP_NAME: "{{ group_name }}"
          GITLAB_PROJ_NAME: "{{ proj_name }}"
          PATH_TO_SSH_KEY: "{{ path_to_store_git_ssh_keys }}"
          IN_DOCKER: "True"
          FILENAME: "main.py"
          MAX_DELAY: "15"
        volumes:
          - "/home/{{ ansible_user_id }}/.ssh/id_ed25519:/home/{{ ansible_user_id }}/.ssh/id_ed25519:ro"
        state: started
      become: yes

    - name: "Create Coders container #2"
      community.docker.docker_container:
        name: coders_2
        restart_policy: always
        image: coders-image:latest
        network_mode: host
        env:
          GITLAB_IP: "{{ hostvars['gitlab']['ansible_host'] }}"
          # GITLAB_TOKEN: "{{ gitlab_root_token }}"
          GITLAB_GROUP_NAME: "{{ group_name }}"
          GITLAB_PROJ_NAME: "{{ proj_name }}"
          PATH_TO_SSH_KEY: "{{ path_to_store_git_ssh_keys }}"
          IN_DOCKER: "True"
          FILENAME: "main.py"
          MAX_DELAY: "7200"
        volumes:
          - "/home/{{ ansible_user_id }}/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro"
        state: started
      become: yes
    
    
