- name: Gitlab configuration
  hosts: gitlab

  vars_files:
    - vars.yml

  tasks:

    - name: Install packages
      apt:
        pkg:
          - curl
          - openssh-server
          - ca-certificates
          - tzdata
          - perl
          - python3-pip
        update_cache: yes
      become: yes

    - name: Add Gitlab package repository
      shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
      become: yes

    - name: Wait 10 seconds after adding gitlab package
      wait_for:
        timeout: 10

    - name: Install Gitlab package
      apt:
        pkg:
          - gitlab-ce
        update_cache: yes
      environment:
        EXTERNAL_URL: "http://{{ ansible_ssh_host }}"
        GITLAB_ROOT_PASSWORD: "{{ gitlab_root_pass }}"
      become: yes

    - name: Wait for a Gitlab boot
      shell: gitlab-ctl status
      register: shell_res
      delay: 30
      until: shell_res.stdout_lines | reject('search','^run') | list | count == 0
      become: yes

    - name: Install pip module 'gitlab'
      pip:
        name:
          - python-gitlab

    - name: Create a Gitlab group
      community.general.gitlab_group:
        validate_certs: false
        api_url: "http://{{ ansible_ssh_host }}"
        api_username: root
        api_password: "{{ gitlab_root_pass }}"
        name: "{{ group_name }}"
        path: "{{ group_name }}"
        visibility: public
        state: present

    - name: Create Gitlab project in created group
      community.general.gitlab_project:
        api_url: "http://{{ ansible_ssh_host }}"
        validate_certs: false
        api_username: root
        api_password: "{{ gitlab_root_pass }}"
        name: "{{ proj_name }}"
        group: "{{ group_name }}"
        issues_enabled: false
        snippets_enabled: true
        initialize_with_readme: false
        #default_branch: main
        visibility: public
        state: present

    - name: Check if repo is already exist
      ansible.builtin.stat:
        path: /var/TTGFinder
      register: proj_folder

    - name: Clone a repo from GitHub
      ansible.builtin.git:
        repo: https://github.com/ATAS-Digital/TTGFinder.git
        dest: /var/TTGFinder
      become: yes
      when: not proj_folder.stat.exists

    - name: Copy bash scripts to repo
      copy:
        src: "gitlab/{{ item }}"
        dest: /var
        mode: +x
        remote_src: false
      with_items:
        - "git-prepare.sh"
        - "ch-dir.sh"
        - "build-maven-project.sh"
      become: yes
    
    - name: Add docker files to repo
      copy:
        src: "gitlab/{{ item }}"
        dest: /var/TTGFinder
        remote_src: false
      with_items:
        #- .gitlab-ci.yml
        - docker-compose.yml
        - Dockerfile
        - nginx/nginx.conf
      become: yes

    - name: Push repo to Gitlab
      expect:
        command: "/var/git-prepare.sh -link http://{{ ansible_ssh_host }}/{{ group_name }}/{{ proj_name }}.git"
        chdir: /var
        responses:
          Username *: "root"
          Password *: "{{ gitlab_root_pass }}"
        timeout: 60
      become: yes
