- name: Configuring Prometheus
  hosts: prometheus
  become: yes

  tasks:

    - name: Install packages
      apt:
        pkg:
          - python3-apt

    - ansible.builtin.import_tasks:
        file: docker-install.yml

    - name: Create folder /srv/prometheus if not exist
      file:
        path: /srv/prometheus
        mode: 0755
        state: directory

    - name: Copy my config to server
      copy:
        src: "prometheus/prometheus.yml"
        dest: "/srv/prometheus"
        remote_src: false

    - name: Copy Dockerfile to Prometheus server
      copy:
        src: "prometheus/Dockerfile.prometheus"
        dest: "/srv/prometheus"
        remote_src: false

    # - name: Build custom Prometheus image
    #   shell: 'docker build -t my-prom-image:latest /srv/prometheus -f /srv/prometheus/Dockerfile.prometheus'
    - name: Build custom Prometheus image
      docker_image:
        build:
          dockerfile: /srv/prometheus/Dockerfile.prometheus
          path: /srv/prometheus
        source: build
        name: my-prom-image
        tag: latest
        state: present

    - name: Create Prometheus container
      community.docker.docker_container:
        name: prometheus
        restart_policy: always
        image: prom/prometheus:latest
        # network_mode: host
        etc_hosts:
          gitlab.my: "{{ hostvars['gitlab']['ansible_host'] }}"
          coders.docker: "{{ hostvars['coders']['ansible_host'] }}"
        volumes:
          - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus_main_data:/prometheus
        command: >
          --config.file=/etc/prometheus/prometheus.yml
          --storage.tsdb.path=/prometheus
          --web.console.libraries=/etc/prometheus/console_libraries
          --web.console.templates=/etc/prometheus/consoles
          --web.enable-lifecycle
        published_ports: "9999:9090"
